### PR TITLE
Update to openjfx19 and jdk17 and gradle 6.7

### LINKED ISSUE #70: Cannot build with gradle 7.4.2 on mac m1
Hello, I've tried to build scenic view on a mac m1 with a recent gradle and jdk.

- The build fails

```
➜  scenic-view  ./gradlew clean build jlink
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
	at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
	at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:109)
	at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
	at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:209)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:107)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:85)
	at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
	at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86)
	at groovy.lang.GroovyObjectSupport.getDefaultMetaClass(GroovyObjectSupport.java:59)
[...]
FAILURE: Build failed with an exception.

* What went wrong:
Could not create an instance of type org.gradle.initialization.DefaultSettings_Decorated.
> Could not initialize class org.codehaus.groovy.reflection.ReflectionCache

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

```

did recreate the wrapper with my system's gradle : `gradle wrapper`. I was able to compile but 

- jlink packaging task fails :

```
➜  scenic-view ✗ ./gradlew jlink      

> Configure project :
Found module name 'org.scenicview.scenicview'

> Task :prepareMergedJarsDir FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':prepareMergedJarsDir' (type 'PrepareMergedJarsDirTask').
  - In plugin 'org.beryx.jlink' type 'org.beryx.jlink.PrepareMergedJarsDirTask' property 'javaHome' of mutable type 'org.gradle.api.provider.Property' is writable.
    
    Reason: Properties of type 'org.gradle.api.provider.Property' are already mutable.
    
    Possible solution: Remove the 'setJavaHome' method.
    
    Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#mutable_type_with_setter for more details about this problem.
  - In plugin 'org.beryx.jlink' type 'org.beryx.jlink.PrepareMergedJarsDirTask' property 'jvmVersion' of mutable type 'org.gradle.api.provider.Property' is writable.
    
    Reason: Properties of type 'org.gradle.api.provider.Property' are already mutable.
    
    Possible solution: Remove the 'setJvmVersion' method.
    
    Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#mutable_type_with_setter for more details about this problem.
  - In plugin 'org.beryx.jlink' type 'org.beryx.jlink.PrepareMergedJarsDirTask' property 'mergedJarsDir' of mutable type 'org.gradle.api.file.DirectoryProperty' is writable.
    
    Reason: Properties of type 'org.gradle.api.file.DirectoryProperty' are already mutable.
    
    Possible solution: Remove the 'setMergedJarsDir' method.
    
    Please refer to https://docs.gradle.org/7.4.2/userguide/validation_problems.html#mutable_type_with_setter for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 382ms
4 actionable tasks: 1 executed, 3 up-to-date
```

---

Additional information :

- gradle version :

```
➜  ~ gradle -version

------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          18.0.1 (Homebrew 18.0.1+0)
OS:           Mac OS X 12.2.1 aarch64
```

 - default jdk :
 
```
➜  ~ /usr/libexec/java_home -V      
Matching Java Virtual Machines (1):
    18.0.1 (arm64) "Homebrew" - "OpenJDK 18.0.1" /opt/homebrew/Cellar/openjdk/18.0.1/libexec/openjdk.jdk/Contents/Home
/opt/homebrew/Cellar/openjdk/18.0.1/libexec/openjdk.jdk/Contents/Home
```

### LINKED ISSUE #75: ScenicView to be compatible with Java17
Hello,

As a lot of applications are moving to Java 17, I would kindly request as a new feature for ScenicView to be compatible with Java 17.

### PR DESCRIPTION
**Pull request by Siedlerchr**
Fixes #75 
Fixes #70 

Superseeds #64

### CODE REVIEW

**Comment by credmond** [comment]
Thanks for this @Siedlerchr. A shame nobody will merge your PR.

Have you noticed less bugs with your newer build?

**Comment by Siedlerchr** [comment]
TBH I haven't used Scene Builder in ages

**Comment by credmond** [comment]
> TBH I haven't used Scene Builder in ages. At least not recently after I made this PR.
> 
Well it works much better with your build. I had thought that it was just a rubbish buggy tool (couldn't understand why people said it was "essential"). I didn't think it was just JDK incompatibilities.

> 
> Yes, that's what sucks here with the whole javafx ecosystem. The say, look there are cool open source libraries babla however, most of them are horrible outdated and nobody even cares about PRs coming in. That sucks the most.

Yep -- I am coming back to JavaFX after 2014 (when I thought it was great).

I was shocked to see the state of the ecosystem. Everything was just broken, yet linked to from a shiny bootstrap website, wanting a yearly fee for certain features. Very sad. They're all controlled by the same absent folks. I won't mention names / companies, but you know what I mean.

Maybe we should fork and publish our own packages -- very easy / free using Github Packages. Don't even need to sign them.

**Comment by JonathanGiles** [comment]
This should be fixed by #78 that was just merged.
